export default{
    "id":"0",
    "name":"root",
    "isFolder":true,
    "items":[{
      "id":"1",
    "name":"public",
    "isFolder":true,
    "items":[{"id":"3",
    "name":"index.html",
    "isFolder":false,
    }]
    },{
      "id":"4",
      "name":"src",
      "isFolder":true,
      "items":[{
        "id":"5",
    "name":"App.js",
    "isFolder":false
      },{"id":"6",
      "name":"package.json",
      "isFolder":false}]
    },{"id":"7",
    "name":"index.js",
    "isFolder":false
    }]
    }